language: php
php:
    - 7.4
    - 8.0

cache:
    directories:
    - "$HOME/.composer/cache"

before_install:
    - nvm install 12

install:
- composer update --no-progress --no-suggest --ansi --prefer-dist

stages:
- name: test
  if: branch = master AND tag IS blank
- name: release
  if: branch = master AND tag IS blank

script: ./vendor/bin/phpunit --coverage-clover=coverage.xml

jobs:
    include:
    -   stage: release
        php: 7.4
        script: |
            npm i -g semantic-release@16 @semantic-release/changelog @semantic-release/git @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/release-notes-generator
            npx semantic-release
